DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS posts;

CREATE TABLE users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username VARCHAR NOT NULL,
  email VARCHAR
);

CREATE TABLE posts (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  user_id BIGINT,
  subject VARCHAR,
  body VARCHAR,
  PRIMARY KEY(id),
  CONSTRAINT fk_user
    FOREIGN KEY(user_id)
      REFERENCES users(id)
);